/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare-env.d.ts` (hash: e9ee154ac381d22a9890108262c0bbca)
interface __BaseEnv_Env {
	ACCESS: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
