/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare-env.d.ts` (hash: e9ee154ac381d22a9890108262c0bbca)
interface __BaseEnv_Env {
	ACCESS: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}

/** Minimal KV surface used by `src/lib/access.ts` (runtime types omitted). */
interface KVNamespace {
	get(key: string): Promise<string | null>;
	put(key: string, value: string): Promise<void>;
}

interface Fetcher {
	fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

interface CloudflareEnv {
	ACCESS?: KVNamespace;
}
